sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t georgexvii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true george/docker-react npm run test
